### ISSUE TITLE
Version bump needed for supported versions

### ISSUE THREAD

**Issue by hailwood** [JetBrains/ideolog#1]
Right now the EAPs are installing version 0.1 which is completely broken.
Can we please have a new release with the supported version bumped?

**Comment by korifey** [comment]
@hailwood it should be usable for small files. Format '{date} | level| category| message' is supported. What is your log format?

**Comment by hailwood** [comment]
@korifey it's the laravel.log so it's pretty standard; The log file simply never opens in the IDE when I've got this plugin installed at version 0.1. No exception is thrown so I can't report it unfortunately.

But In this issue I'm referring to the fact that version 0.1 is available for IDE version 171+ however we're up to 0.2.3 but that only works for 171.4424—171.* meaning the latest EAP will only install version 0.1.

**Comment by mfilippov** [comment]
New plugin version compatible with 2017.1 deployed.

**Comment by hailwood** [comment]
@mfilippov thanks for that but the latest EAP is:

PhpStorm 2017.2 EAP
Build #PS-172.3317.57, built on July 12, 2017

Could we bump the supported version to include 172.* as well so I can install it and test?

--
Matt

**Comment by mfilippov** [comment]
@hailwood thanks for the feedback I try to add support 172.+ little bit later.

**Comment by mfilippov** [comment]
@hailwood Support for 172.* ready.
