### ISSUE TITLE
Cannot set foreground/background color for patterns

### ISSUE THREAD

**Issue by MilanStaffehl** [JetBrains/ideolog#102]
Since updating PyCharm CE to 2020.2 I can no longer set colors in the settings for new and existing patterns. Clicking on the field highlights it but I cannot choose a color nor type a hex value. I am able to highlight an exisiting hex code but not to change it.

**Comment by phena109** [comment]
Confirmed, and the same issue is #99

**Comment by zolotov88** [comment]
Same issue

**Comment by AndreasVenturini** [comment]
I have the same issue.

**Comment by jamescodesthings** [comment]
Same issue on Webstorm 2020.2

**Comment by MilanStaffehl** [comment]
Tried again, works now after update to PyCharm CE 2020.2.2.

**Comment by VladRassokhin** [comment]
Seems fixed in latest plugin update (version 202.0.25.0), tested with GoLand 2020.2.3

**Comment by markus-zhang** [comment]
Same issue on Datagrip 2020.2.2. Cannot upgrade to most recent version as most recent version has a bug.
