### ISSUE TITLE
Please reserve the ansi color in log file

### ISSUE THREAD

**Issue by maimake** [JetBrains/ideolog#113]
## I have a log file that contains Ansi Color controllers like :

![image](https://user-images.githubusercontent.com/492028/114968001-0aee0f00-9ea8-11eb-96d5-47c5aec02b6b.png)

## It would be better looking like:

![image](https://user-images.githubusercontent.com/492028/114968403-d7f84b00-9ea8-11eb-8640-02fdf2605d5a.png)

The plugin's name is https://plugins.jetbrains.com/plugin/9707-ansi-highlighter

**Comment by smirok** [comment]
Close this one as a #140 duplicate
