### ISSUE TITLE
"Highlight match" action is not working

### ISSUE THREAD

**Issue by LinHuiG** [JetBrains/ideolog#123]
"Highlight match" action is not working. please prioritize it.

**Comment by LinHuiG** [comment]
it's important for me

**Comment by LauLaman** [comment]
not working here either

**Comment by daje-x** [comment]
I'm here too.

**Comment by KristianMischke** [comment]
would be very helpful

**Comment by ArtemKar123** [comment]
Added in #169. Will be released in the next version. Thanks for your feedback!
