### ISSUE TITLE
Settings dialog broken in 2017.3 EAP

### ISSUE THREAD

**Issue by kdambekalns** [JetBrains/ideolog#13]
The wiki page at https://github.com/JetBrains/ideolog/wiki/Custom-Log-Formats sounded promising, but where do I edit those settings? Here are two screenshots showing the issue:

*2017.2*
<img width="1061" alt="ps-172_4155_25" src="https://user-images.githubusercontent.com/95873/30362942-9a59e712-985e-11e7-9e28-938a034c8bbc.png">

*2017.3 EAP*
<img width="1025" alt="ps-173_2099_16" src="https://user-images.githubusercontent.com/95873/30362949-9e1d0b9a-985e-11e7-9d9d-b4bfda619ea2.png">

**Comment by knah** [comment]
Don't these buttons work? The "Add" button being gray is a bit odd, but it's brighter than two other buttons, so I assume it's just the way Mac OS is and "Add" is actually enabled.
![image](https://user-images.githubusercontent.com/4705494/30363142-c7acd14e-9867-11e7-9c11-c3f43842daee.png)

As for 2017.3 EAP not having log formats - we haven't released a version for that IDEA build yet.

**Comment by kdambekalns** [comment]
I 2017.2 everything works fine in the dialog (I didn't manage to get my specific log format working so far, but that's another story).

As for 2017.3, at least the plugin did not get detected as incompatible. :)

**Comment by Deniis** [comment]
yes, plugin does not work in 2017.2.3, 2017.2.4

**Comment by mfilippov** [comment]
@Deniis The latest version should work. Could you check it?

**Comment by kdambekalns** [comment]
Works fine by now…
