### ISSUE TITLE
Support default `loguru` format in PyCharm

### ISSUE THREAD

**Issue by peter-gy** [JetBrains/ideolog#130]
In PyCharm, it would provide an extremely nice Developer Experience to have support for the default [`loguru`](https://github.com/Delgan/loguru) format.

Currently it looks rather unattractive:

<img width="933" alt="Screenshot 2022-03-28 at 18 28 34" src="https://user-images.githubusercontent.com/40776291/160444213-76a4449d-d54f-4247-862e-363da06f77b2.png">

**Comment by deployment-ian** [comment]
I would also like for this to be a feature

**Comment by mcarans** [comment]
Yes me too

**Comment by iMagist486** [comment]
[loguru.zip](https://github.com/JetBrains/ideolog/files/12288126/loguru.zip)

**Comment by HenryXiaoYang** [comment]
> [loguru.zip](https://github.com/JetBrains/ideolog/files/12288126/loguru.zip)

Thank you so much

**Comment by pawrequest** [comment]
hi i think i must be using this wrong?

i installed loguru and it logs fine, viewing log pycharm complains unknown format, i click 'configure log formats' -> import and select the provided xml. it seems to import fine, is enabled, but pycharm still complaining and no highlighting? restarted pycharm but same

```
import pytest
from loguru import logger

logger.add('test.log', rotation='1 minute')


@pytest.mark.asyncio
async def test_log():
    logger.info("test")

```
