### ISSUE TITLE
how to navigate?

### ISSUE THREAD

**Issue by NamedAngel** [JetBrains/ideolog#135]
how to navigate to source by the path below? I press F7, but navigate to incorrect file.
![image](https://user-images.githubusercontent.com/47881101/165877141-9fbfaf03-329e-4f7a-8ebb-a51cff771489.png)

**Comment by smirok** [comment]
Hi @NamedAngel,

Navigation to the source is based on the "category" from the parsing pattern. Here is a link to the file, but it is not highlighted because you have used a relative path instead of an absolute one.
