### ISSUE TITLE
Path does not link to source code

### ISSUE THREAD

**Issue by zeroarst** [JetBrains/ideolog#142]
This path is valid and it is my source code
`D:\WebStorm\Projects\reward-miles\api\src\controllers\Api\airline.controller.ts:5:16`
But in the log cannot link to it.
![image](https://user-images.githubusercontent.com/1834837/224480990-0dc44df2-d428-4bf2-9e28-02027495128b.png)

With Visual Studio Code, it can.
![image](https://user-images.githubusercontent.com/1834837/224481036-e5a1fec8-514a-4d2e-9424-4155a6a96edb.png)

**Comment by ArtemKar123** [comment]
Fixed in #174. Will be released in the next version. Thanks for your feedback!
