### ISSUE TITLE
ideolog not work

### ISSUE THREAD

**Issue by ciahua** [JetBrains/ideolog#143]
I config the ideolog and write a log file, content as below:
2021-01-21 11:19:19.111  INFO 10808 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/9.0.12

pattern:
^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s*([A-Z]*)\s\d*\s\-{3}\s(\[.*\]).*\: .*$

jetbrains idea version: IntelliJ IDEA 2022.2.3 (Ultimate Edition)

ideolog version is the latest.

what's wrong with it?

![微信截图_20230327222138](https://user-images.githubusercontent.com/37827583/227971212-4082b8f5-f825-478a-896d-39e7762a07c0.png)
![微信截图_20230327222119](https://user-images.githubusercontent.com/37827583/227971390-32bbfacc-35d1-415f-8b9c-fd72cd67b4ff.png)
![微信截图_20230327222057](https://user-images.githubusercontent.com/37827583/227971401-a81af6d6-e419-4bf7-9c72-bc2a11d4e65b.png)
![微信截图_20230327222033](https://user-images.githubusercontent.com/37827583/227971410-d401030a-db82-49a4-9da5-acd3bb256cac.png)

**Comment by ArtemKar123** [comment]
Looks, like your pattern doesn't work
https://regex101.com/r/FArdI2/1

**Comment by ArtemKar123** [comment]
Looks, like your pattern doesn't work
https://regex101.com/r/FArdI2/1

**Comment by ArtemKar123** [comment]
Looks like your pattern doesn't work
https://regex101.com/r/FArdI2/2
