### ISSUE TITLE
Changing edit-size threshold does not apply to open editors

### ISSUE THREAD

**Issue by Vampire** [JetBrains/ideolog#157]
If you change the size threshold for being able to edit a file, the read-only state for existing editors is not updated.
You first have to close and reopen the file to change the read-only state.

**Comment by smirok** [comment]
Hi @Vampire! It's not safe to update `read-only` state of the opened editor, as it shouldn't be updated during the file modification, which may occur asynchronously.

**Comment by Vampire** [comment]
But if you use the normal read-only functionality of the editor, you can do it quite fine. :-/
Maybe you should just set that instead, so the I as user can simply use the standard functionality to make the file read/write?
Talking about this one:
![image](https://github.com/user-attachments/assets/de894ab7-c6a9-4b85-80e1-1f18b69e4609)
I can toggle it any time and the already open file adjust accordingly instantly without the need to close and reopen the file.

**Comment by smirok** [comment]
Good catch, thanks! I'll try it out

**Comment by smirok** [comment]
Hi! There is a problem with the read-only functionality of the editor: it works at the file level. 

So if you make a log file read-only using this button, then new logs won't be appended to the file unless you make it writable back.

**Comment by Vampire** [comment]
Oh, that's bad of course. :-(

**Comment by smirok** [comment]
So far I'd suggest to close and reopen the file to change the read-only state
