### ISSUE TITLE
How / where is "Intention to highlight distance between events (marks time as red)"?

### ISSUE THREAD

**Issue by Vampire** [JetBrains/ideolog#159]
I've seen in the readme that there should be an "Intention to highlight distance between events (marks time as red)" which sounds very useful.
Unfortunately I can nowhere identify such an intention.

**Comment by smirok** [comment]
Hi @Vampire! You could call the intention from the context while the cursor is placed on the date.

![ideolog-time-intention](https://github.com/user-attachments/assets/6479fbc7-af1c-45d9-8529-7f166e5dee3f)

**Comment by Vampire** [comment]
Ah, thanks, there it is hidden :-D
Besides that it does not really work as expected for me, but neither do the other intentions or the plugin at all. :-/
But I'll create a separate issue for that.
Maybe you'll be able to also have a look there when I did. :-)

**Comment by uuf6429** [comment]
I'm also very interested in this feature, but I don't get any such context actions at all, anywhere in the log. Should I report a new issue?

**Comment by smirok** [comment]
Hi @uuf6429

Yes, please
