### ISSUE TITLE
Allow clearing of log files

### ISSUE THREAD

**Issue by JPry** [JetBrains/ideolog#16]
I understand that having log files as read-only is intentional. I would like a way to still use this plugin but be able to clear log files.

The reason for this is that I use the log files during local development, but it is easier to empty the log file contents after I've identified issues rather than keep appending to the existing issues that have been fixed.

This could potentially be an option somewhere in Settings that is disabled by default, which would maintain the current behavior. It might also be nice to specify individual log files that could be opened as read/write instead of read-only.

**Comment by hypersw** [comment]
So do you want to edit the log text, or to clear the log file?

**Comment by JPry** [comment]
In my usage I typically just clear the log file. This is quickest solution for my use case.

**Comment by hypersw** [comment]
Clearing the log file does not contradict with the current support for large files in "R/O with append" mode — as arbitrary editing does. So if you put the issue as "allow clearing the log file", it gets much more probable IMHO.

**Comment by thanosIrodotou** [comment]
I guess the main reason the files are write locked is that one can easily mess up with the line and break the regexp matching. Deleting lines or clearing should be ok though.

**Comment by hypersw** [comment]
Basically, changing the length of the document and the number of line breaks is not OK for the initial implementation (this includes replacing whole lines with an empty string as well). Appending to the end of the document were specifically allowed, being the typical log viewing scenario and not affecting the larger body of the document.

**Comment by G-Rath** [comment]
I'd personally like the option to edit my log files. 

When I'm using log files in development, it's often for viewing specific data that I'm outputting as part of testing, and so often want to clear or remove part of a log file. 

I've actually only just had my log files become read-only: I was editing a WordPress debug.log, restarted IntelliJ, and was then told I couldn't edit my log file as it's read-only, all literally 5 minutes ago.

Normally when editing a file that's read-only, IntelliJ offers me a warning and choice before allowing the edit. I can't find anyway to make my log files writable while still using this plugin, and so sadly I'm going to remove it. 

I'd like to see this change, so I could control what log files are made read-only. Ideally I'd like to see .log files be treated the same as (for example) node_modules and vendor folders.

**Comment by tomandersen** [comment]
How would one clear a log file? I am going to uninstall I guess.

**Comment by knah** [comment]
We will consider some support for toggle-able editing of log files (with loss of features that depend on it being read-only). There are also some difficulties with allowing limited editing, such as "deleting whole lines" or "clearing with ctrl+A then delete" - I'm not sure if one can express such limitation through IDEA's APIs.
As for clearing the file, doesn't deleting it work? Or opening it it overwrite mode in code that creates it?

Additionally, there should be line-hiding feature ("Hide lines above this") to ease reading smaller segments of log files.

**Comment by G-Rath** [comment]
What features are dependent on the file being read-only?

**Comment by knah** [comment]
Currently - most of highlighting and log format detection, probably something else I don't remember about. I have already said this elsewhere, but this plugin was intended for use with very large log files - 1 MB and over (and even over current IDEA limit). As such, we cache some information regarding line positions and message boundaries. This information would be invalidated by edits to the file.

We could consider not relying on this caching for smaller log files, and making only sufficiently large files read-only. It will still need some testing and consideration.

**Comment by knah** [comment]
I've added the ability to make log files writable depending on their size. In my experiments, though, editing was relatively slow. The settings is found with the rest of Ideolog's settings.

Although this is not published (yet).
