### ISSUE TITLE
Keymap for next error doesn't work

### ISSUE THREAD

**Issue by pawelkuras** [JetBrains/ideolog#17]
**Go To Next Error in Log** (Shift+F7) keymap does nothing.

Tried on idea.log and custom log.

**Comment by knah** [comment]
What OS, IDEA and Ideolog versions are you on?

**Comment by pawelkuras** [comment]
I'm not sure when it started working, but it does now.  I am currently on Windows 10, IDEA 2017.3.5 (Ultimate), and Ideolog 173.0.7.0
