### ISSUE TITLE
Doesn't seems to work on Intellij 2017.2.5

### ISSUE THREAD

**Issue by jaylemur** [JetBrains/ideolog#18]
Hi !

IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017

Installed Version: 172.0.4.0 through the plugin installer

If I open a .log file, I cannot access to the ideolog features.

**Comment by jfcabral** [comment]
x2

Specs:
IntelliJ IDEA 2017.2.6
Build #IC-172.4574.11, built on November 13, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by jaylemur** [comment]
Also unsuccessfull with :

IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017
Licensed to Post CH AG

JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by Saandji** [comment]
Any updates on this? doesn't work in the latest version:

IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

and "opening log file outside the project" also doesn't help.

**Comment by mfilippov** [comment]
@jaylemur @jfcabral  @Saandji Could you try 172.0.5.0 version. I checked it on 2017.2.6.

**Comment by Saandji** [comment]
@mfilippov just checked with the latest version. I've got my global URLs highlighted, but nothing more.

**Comment by NJKruczek** [comment]
I just tried with IDEA 2017.3.3 with version 173.0.6.0 and I can't open log files anymore.

**Comment by emudojo** [comment]
nope, can't open them (they open, but nothing special happens)

**Comment by knah** [comment]
Please elaborate for all these instances where "nothing happens" or "can't open". First, check if you have Ideolog settings page. You should be able to find it by typing "ideolog" into search in settings dialog.
![image](https://user-images.githubusercontent.com/4705494/35385842-0b2e9594-01ca-11e8-8c93-e6221078d0b9.png)
If it's there, enable the heat map, then save the settings.
Open your log file. If it's already open, close it and open it again.
See if it has green scrollbar. If it does, but you can't see any highlightings - probably you don't have a configured format for this log, or something is wrong with your configuration.
If it doesn't have a green scrollbar, even though it's enabled in settings - please report exact versions of IDEA and Ideolog you're using.

**Comment by jfcabral** [comment]
Thanks @mfilippov and @knah, I've just tested it in the latest 2018.1 version and it is working perfectly 👍
