### ISSUE TITLE
"Log Format Not Recognized" Warning Message, Pattern Applied, Logs Colored, Warning Cleared, OG Regex Not Working

### ISSUE THREAD

**Issue by aaronhunter1088** [JetBrains/ideolog#188]
Hi Jetbrains,

I noticed the above mentioned warning message while reviewing my log file one day and decided to fix the issue rather than clicking "Hide this notification," or "Don't show again". 

I am using Log4j2 to print to the console and my log file, and this is my pattern I am using -->
[%-6level] %d{MM-dd-yyyy hh:mm:ss.SSS a} [Method:%M] %c:%L :: %msg%n (1*) (2**)
(1*) For the console, the pattern changes from [%-6level] to %highlight{%-6level}
(FILE: [log4j2.properties.txt](https://github.com/JetBrains/ideolog/files/15346119/log4j2.properties.txt))

Using regex101.com, I was able to create a regex and verified that it matches my logs -->
Regex:
<img width="1173" alt="Screenshot 2024-05-17 at 3 46 07 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/11fe1b31-c299-476c-9d3e-7a3a106e6158">

I set the regex as my message pattern, but it still did not clear the warning or color my logs in my log file (the console is being colored because of the highlighting).     
My message pattern is --> ^(\\[[A-Z]{4,6}\\])\s?(\d{2}.\d{2}.\d{4})\s?(\d{2}\:\d{2}\:\d{2}\.\d{3}\s?[A-Z]{2})\\s?\\[.*\\]\s?-\s?(.*)\n$
My message start pattern is --> ^\\[
My time format is --> MM-dd-yyyy hh:mm:ss.SSS a

IntelliJ Log Highlighting --> 
<img width="842" alt="Screenshot 2024-05-17 at 5 06 48 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/568a8576-0917-49c2-a19d-60feb3d1ed73">

IntelliJ Log Patterns -->
<img width="552" alt="Screenshot 2024-05-17 at 3 54 54 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/b655fd30-5644-478c-8413-91e5dc4c27c3">

When I checked my log file, it was still not coloring my logs as I expected.
(2**) I removed the brackets around the log level in my log4j2.properties file, making my pattern become the following:
%-6level %d{MM-dd-yyyy hh:mm:ss.SSS a} [%c:%M:%L] - %msg%n

After making this change, I noticed my log file began to color my logs, but the warning message remained.
File logs -->
<img width="1132" alt="Screenshot 2024-05-17 at 3 51 05 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/eb1080db-b7f1-4436-a43e-afb77c4d337f">

When I attempt to find my message pattern using Command + F (Find), using the regex matching option, I had to change my pattern in order for it to match all logs -->
From --> ^(\\[[A-Z]{4,6}\\])\s?(\d{2}.\d{2}.\d{4})\s?(\d{2}\:\d{2}\:\d{2}\.\d{3}\s?[A-Z]{2})\s?\[.*\]\s?-\s?(.*)\n$
To --> ^(\\[[A-Z].{4,6}\\])(?s)(.*)$

New Values -->
My message pattern is --> ^(\\[[A-Z].{4,6}\\])(?s)(.*)$
My message start pattern is --> ^\\[
My time format is --> MM-dd-yyyy hh:mm:ss.SSS a

Find Regex in Log File -->
<img width="1143" alt="Screenshot 2024-05-17 at 4 11 46 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/60a1ec9e-5f1c-44a1-ba6b-7c1101f0215e">

Find Regex in Console logs -->
<img width="786" alt="Screenshot 2024-05-17 at 4 34 01 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/6c293383-1469-4df1-9ed0-348a6bee8d7b">

Since my log file no longer contains the brackets around the level, I changed my message pattern and message start pattern one final time to be -->
Message pattern --> ^(\w*)(?s)(.*)$
Message start pattern --> ^\w
My time format is --> MM-dd-yyyy hh:mm:ss.SSS a

Using these final values still worked and colored my logs, and after a lot of hard work, the warning message also disappeared. 
Since I see others are having troubles with this, I am still posting this in hopes that it helps anyone else who may be struggling.

Warning Message Cleared:
<img width="1110" alt="Screenshot 2024-05-17 at 4 48 47 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/9a6a86fe-fcbb-4fff-b30d-b07827823a01">

Working IntelliJ Log Patterns -->
<img width="416" alt="Screenshot 2024-05-17 at 4 32 10 AM" src="https://github.com/JetBrains/ideolog/assets/19511224/5bb96454-6a74-41cc-9a91-f008996335fc">

**Comment by wp4nuv** [comment]
This happens to me, but it is inversed. The monolog format regexp works in regex-101, and PHPStorm doesn't complain about the format, but the highlighting fails to save the color. The saved color for the existing examples is reflected in the Action column, but for custom ones, you can select the color, but once you hit OK, nothing is saved.  Selecting __BOLD__ or _italic_ is reflected in the Action column.

**Comment by smirok** [comment]
Hi @aaronhunter1088 @wp4nuv! Thank you for your instructions and comments.

Have you tried using the tips from the [wiki documentation](https://github.com/JetBrains/ideolog/wiki)? If so, were they useful to you?

**Comment by aaronhunter1088** [comment]
@smirok, no, i didn't use those tips from the wiki. i wasn't aware of them. i did a lot of googling and trial and error. but now that you've made them aware to me, i did check them out, and it looks like the kind of info i would have wanted the night i worked on all this. 😆 but again, thanks for making me aware of this wiki 😊 

i'm going to close this now, seeing in the wiki that if there is an issue with the log pattern, it is ignored, and that is a Known Issue. And, that was the final statement in my title, OG Regex Not Working, now answered (It seems as though that was by design, on purpose).

**Comment by smirok** [comment]
@aaronhunter1088 Thank you for the feedback, I'll add the link to wiki in both log format and highlighting pattern creation tool windows.
