### ISSUE TITLE
UE issue

### ISSUE THREAD

**Issue by zhaozhatian** [JetBrains/ideolog#194]
when the log file size big enough, i find it's impossible to empty the log file, even in the local enviroment. 
this problem is just bothering me all the time.

**Comment by smirok** [comment]
Hi @zhaozhatian!

There is a setting in "Settings -> Editor -> Log Highlighting" that allows you to edit log files smaller than a certain size. By default, it's allowed to edit files smaller than 16 KB, but you can always adjust the threshold to suit your needs.

However, do you need to empty the log file from the editor? You can still delete the entire log file if you want.

**Comment by smirok** [comment]
I close this issue as a #94 duplicate.
