### ISSUE TITLE
Add `tail` and `tail -f` modes

### ISSUE THREAD

**Issue by vjpr** [JetBrains/ideolog#22]
My log files are usually massive, but I am only interested in the tail.

**Comment by knah** [comment]
Summoning @IvanPashchenko here, as he was the one originally implementing something similar originally.

**Comment by IvanPashchenko** [comment]
@knah this is going to take a lot of time to implement properly, as I did a lot of hacks for that, removing asserts in the platform (we were basically "editing" a read-only file, which is not a good thing to do obviously) etc. It's definitely possible, I think, and I'd like to implement that — but not right now.

**Comment by smirok** [comment]
Hi! We've added `tail` and `tail -f` support for the log files opened in [New Terminal](https://www.jetbrains.com/help/idea/terminal-emulator.html#new-terminal). 
You need both Ideolog and New Terminal plugins to experience it.
