### ISSUE TITLE
Rider+ideolog freeze after opening diagnostic build log

### ISSUE THREAD

**Issue by gumowy-kaczak** [JetBrains/ideolog#25]
Rider freezes when opening diagnostic build log. It tries to process the file, but it never finishes (15 mins was not enough, and memory consumption was constantly growing).

Reproduction steps:
1. Run Rider.
1. Create "New solution" and select "ASP.NET Core Empty".
1. Select menu "Build" -> "Rebuild Solution with Diagnostics".
Yours Rider instance should hang now. 

Environment:
JetBrains Rider 2017.2.1
Build #RD-172.4144.1873, built on November 12, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin version:
Ideolog
Version: 172.0.5.0

Attachments:
- Problematic log file: [JetBrainsLog.ReSharperBuild_2017_12_24_20_25_47_2505.log](https://github.com/JetBrains/ideolog/files/1585040/JetBrainsLog.ReSharperBuild_2017_12_24_20_25_47_2505.log)
- Resources utilization
![utilization](https://user-images.githubusercontent.com/15362706/34329038-df7ef0ce-e8f1-11e7-8854-721d662fabf5.JPG)

**Comment by gumowy-kaczak** [comment]
Still an issue in newest versions.

JetBrains Rider 2017.3
Build #RD-173.3994.1125, built on December 26, 2017
JRE: 1.8.0_152-release-1024-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin version:
Ideolog
Version: 173.0.5.0

**Comment by SQReder** [comment]
It's still an issue. 

JetBrains Rider 2018.3 EAP
Build #RD-183.4704.20, built on November 27, 2018
Rider EAP User
Expiration date: December 27, 2018
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
