### ISSUE TITLE
Cannot edit file when this plugin installed

### ISSUE THREAD

**Issue by mnabialek** [JetBrains/ideolog#27]
When I have this plugin installed I cannot edit content of the file. For example if I manually create *abc.log* file I cannot put any content in it. Is it desired behaviour or a bug? I often for example when running tests look at error log, but later I often empty content of the file. Now I need to use 3rd party editor to remove file content if I have this plugin enabled.

**Comment by knah** [comment]
Editing of log files should be possible in the next release with a setting to toggle it (see #16).
