### ISSUE TITLE
What are Patterns for?

### ISSUE THREAD

**Issue by mesketh** [JetBrains/ideolog#29]
Thanks for the plugin.

Bit confused about the requirement for Patterns - the examples quote matching on severity e.g. info, etc.. Do I need these if I have a capture group for Severity? 

Here's a sample of my log: 

```bash
[SOME_USER] 16:45:52.222 INFO  VehicleController - Vehicle search found 1 results
```

Here's my "Message pattern" for my Log Format: 

```bash
^\[([A-Z_]+)\]\s([0-9:\.]+)\s([[:word:]]+)[[:space:]]+([[:word:]]+)(.*)$
```

Why is this stuff not on the wiki or should I be able to figure this out (self documenting?!).

Many thanks

**Comment by knah** [comment]
The "Patterns" part of configuration is for setting up highlighting. Probably we should rename them to "Highlighting patterns" or something.

The three bundled patterns highlight lines with severities of Error, Warning and Info. You can also add your own highlighting patterns here, for example to highlights all log messages from VehicleController.

These operate after log message was parsed using your Log Format. Patterns are applied to each field (specified by capture groups), and perform their corresponding action if there is a match.

I've create a [wiki page](https://github.com/JetBrains/ideolog/wiki/Highlighting-Patterns) documenting this part.

Hope it helps!

As a side note, I haven't seen [[:word:]] and [[:space:]] character classes in official Java documentation, and they don't seem to work on some random online regex validator. Consider replacing them with \w and \s respectively. Other than that, it looks just fine.

**Comment by mesketh** [comment]
Thanks guys - got it working now. Good job on the quick response + wiki page.
