### ISSUE TITLE
Compatibility with IDEA 2018.2

### ISSUE THREAD

**Issue by AndreyAkinshin** [JetBrains/ideolog#30]

**Comment by xstable** [comment]
+1

**Comment by mfilippov** [comment]
Ready to use.

**Comment by xstable** [comment]
Do you create an patch? Currently it does not work on: 
![auswahl_719](https://user-images.githubusercontent.com/1778068/40236664-99aa3840-5aae-11e8-8faa-1f88a7c856d1.jpg)
