### ISSUE TITLE
Is it should work on PhpShtorm?

### ISSUE THREAD

**Issue by mubat** [JetBrains/ideolog#31]
I tried to use plugin at PhpShtorm 2017.3 in Yii php project.
I created new log format:

> **Pattern** (?im)^([\d-: ]+)\[((?:\d{1,3}.){3}\d{1,3})\]\[-\]\[-\]\[(\w+)\]\[([\w\\:\d]+)\] (.*) 
> **Message start pattern** ^\d
> **Time format** yyyy-MM-dd HH:mm:ss

Standard log record at Yii project seems like:
```
2017-09-27 14:52:49 [127.0.0.1][-][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: api\modules\v1\models\General::district.name in /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/base/Component.php:143
Stack trace:
#0 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/db/BaseActiveRecord.php(286): yii\base\Component->__get('district.name')
#1 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/base/ArrayableTrait.php(120): yii\db\BaseActiveRecord->__get('district.name')
#2 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/rest/Serializer.php(292): yii\base\Model->toArray(Array, Array)
#3 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/rest/Serializer.php(188): yii\rest\Serializer->serializeModels(Array)
#4 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/rest/Serializer.php(152): yii\rest\Serializer->serializeDataProvider(Object(yii\data\ActiveDataProvider))
#5 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/rest/Controller.php(97): yii\rest\Serializer->serialize(Object(yii\data\ActiveDataProvider))
#6 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/rest/Controller.php(75): yii\rest\Controller->serializeData(Object(yii\data\ActiveDataProvider))
#7 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/base/Controller.php(156): yii\rest\Controller->afterAction(Object(yii\rest\IndexAction), Object(yii\data\ActiveDataProvider))
#8 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('index', Array)
#9 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('v1/object/index', Array)
#10 /home/oleg/Projects/crm-application/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /home/oleg/Projects/crm-application/api/web/index.php(18): yii\base\Application->run()
#12 {main}
2017-09-27 14:52:49 [127.0.0.1][-][-][info][application] $_SERVER = [
    'REDIRECT_REDIRECT_STATUS' => '200'
    'REDIRECT_STATUS' => '200'
    'HTTP_USER_AGENT' => 'ApiDebugger v2.0.1'
    'HTTP_HOST' => 'crm.dev'
    'HTTP_CONNECTION' => 'Keep-Alive'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'SERVER_SIGNATURE' => '<address>Apache/2.4.18 (Ubuntu) Server at crm.dev Port 80</address>
'
    'SERVER_SOFTWARE' => 'Apache/2.4.18 (Ubuntu)'
    'SERVER_NAME' => 'crm.dev'
    'SERVER_ADDR' => '127.0.0.1'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '127.0.0.1'
    'DOCUMENT_ROOT' => '/home/oleg/Projects/crm-application/'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/home/oleg/Projects/crm-application/'
    'SERVER_ADMIN' => 'webmaster@localhost'
    'SCRIPT_FILENAME' => '/home/oleg/Projects/crm-application/api/web/index.php'
    'REMOTE_PORT' => '34204'
    'REDIRECT_URL' => '/api/web//v1/object'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'REQUEST_URI' => '/api/v1/object'
    'SCRIPT_NAME' => '/api/web/index.php'
    'PHP_SELF' => '/api/web/index.php'
    'REQUEST_TIME_FLOAT' => 1506523969.49
    'REQUEST_TIME' => 1506523969
]
```

I check pattern at online regex tester and it works: https://www.ocpsoft.org/tutorials/regular-expressions/java-visual-regex-tester/

**Is it should works? Is it an issue?**

**Comment by knah** [comment]
I have no idea what your visual regex tester does wrong, but your regex suffers from extreme lack of escaping. It doesn't even work with your pattern and log sample for me.

The correct regex that matches both messages provided by you is `^([\d-: ]+)\[((?:\d{1,3}.){3}\d{1,3})\]\[\-\]\[\-\]\[(\w+)\]\[([\w\:\d\\]+)\] (.*)`. Note that all square braces that do not denote a capture group are escaped. I also added a backslash to category capture group so that it matches `yii\base\UnknownPropertyException`.

That aside, we are planning to add visual regex validation and testing aids to Ideolog sometime soon.

**Comment by mubat** [comment]
@knah How plugin should be configured?
What means `Patterns` settings block? Is patterns inside it should include previous data, or only validate category group?
![screenshot from 2018-02-22 11-32-54](https://user-images.githubusercontent.com/3623986/36530689-72bc606e-17c4-11e8-96a7-6f8813795e59.png)
![screenshot from 2018-02-22 11-33-11](https://user-images.githubusercontent.com/3623986/36530695-76592130-17c4-11e8-9fce-b912d52875fe.png)

**Comment by knah** [comment]
"Patterns" specify how to highlight your logs. See https://github.com/JetBrains/ideolog/issues/29 and https://github.com/JetBrains/ideolog/wiki/Highlighting-Patterns for more info.

**Comment by khalwat** [comment]
I realize this is a super-old thread, but in case anyone else finds it -- here's a regex that works with Yii2 (and thus Craft CMS) logs:

Message pattern:
```
^([\d-: ]+)\[(.*?)\]\[(.*?)\]\[(.*?)\]\[(.*?)\]\[(.*?)\] (.*)
```

Message start pattern:
```
^\d
```

Time format:
```
yyyy-MM-dd HH:mm:ss
```

Time capture group:
```
1
```

Severity capture group:
```
5
```

Category capture group:
```
4
```

<img width="695" alt="Screen Shot 2020-09-18 at 3 56 40 PM" src="https://user-images.githubusercontent.com/7570798/93669286-33707080-fa61-11ea-8d39-9233bea9d7c3.png">

...and then for the Patterns, you'll want to add a couple:

Profile:
```
^\s*p(rofile.*)?\s*$
```

Debug:
```
^\s*d(ebug)?\s*$
```

<img width="439" alt="Screen Shot 2020-09-19 at 10 20 24 AM" src="https://user-images.githubusercontent.com/7570798/93669384-c6a9a600-fa61-11ea-8b16-7a05630fda53.png">
