### ISSUE TITLE
Integrate with test runner

### ISSUE THREAD

**Issue by reitzig** [JetBrains/ideolog#34]
Looking through the list of features, those are exactly what I want when sifting through output of unit and integration tests -- which end up in the test runner tool window, not a log file.

So it would be cool if test output could be treated as if was stored in a `.log` file, and have Ideolog features.

A quick workaround would be a function "Open in new Scratch" in the test runner, but I guess this is the wrong place for that?

**Comment by smirok** [comment]
Hi! Thank you for your report. I close this issue as a #46 duplicate.
