### ISSUE TITLE
Tail mode

### ISSUE THREAD

**Issue by NikGovorov** [JetBrains/ideolog#37]
Hi guys,

Does tail mode that is demonstrated on the video below actually work in version 181.0.7.0?

https://youtu.be/ZwVHJGSUhAU?t=216

```
JetBrains Rider 2018.1 EAP
Build #RD-181.4379.788, built on April 7, 2018
Rider EAP User
Expiration date: May 7, 2018
JRE: 1.8.0_152-release-1136-b23 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by IvanPashchenko** [comment]
@NikGovorov no, it doesn't
https://github.com/JetBrains/ideolog/issues/22#issuecomment-347553621

**Comment by NikGovorov** [comment]
Thanks @IvanPashchenko!
