### ISSUE TITLE
Suggest Ideolog when *.log file is opened

### ISSUE THREAD

**Issue by van800** [JetBrains/ideolog#39]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206116479-How-to-enable-plugin-detection-by-file-extension-

**Comment by knah** [comment]
It should already work this way, if there is an appropriate version of Ideolog available. If it somehow doesn't, probably something broke on plugin repository again.

**Comment by van800** [comment]
You are right, for me it works on 18.1.1 Nighlty.
It doesn't work for me on Rider 18.2 locally started from SDK with Unity support plugin.
