### ISSUE TITLE
Add way to cleanup log file

### ISSUE THREAD

**Issue by mfilippov** [JetBrains/ideolog#41]

**Comment by knah** [comment]
Any details? Why is Ctrl+A, Del not enough? I know that logs are normally read-only, but we have settings for that.

**Comment by mfilippov** [comment]
Maybe we can add action in some visible place to cleanup up or suggestion about read-only mode when a user tries to clean up.

**Comment by dcdiogo** [comment]
> Any details? Why is Ctrl+A, Del not enough? I know that logs are normally read-only, but we have settings for that.

I'm using Laravel framework and sometimes Ctrl+A, Del not clear log file (it seems log file is read only), but clearing it through terminal is working (command is: `$ > storage/logs/laravel.log`)

**Comment by reloxx13** [comment]
just uninstalled this plugin cuz it did not let me clear the log
usability > appearence

**Comment by knah** [comment]
Given that no useful input has been provided here, I'll close the ticket and refer you to #16.
Ideolog makes large log files readonly for performance reasons. There is a setting for what it considers "large". Change it if you want to clear your logs in editor, even if I have no idea what kind of workflow requires that.
![image](https://user-images.githubusercontent.com/4705494/46954728-9f861500-d091-11e8-9a83-2487004e9863.png)

**Comment by mehov** [comment]
> Why is Ctrl+A, Del not enough?

This is the first thing I tried and it says "*The view is read-only*".

All I want is a quick button to empty the log file
