### ISSUE TITLE
Links are opened multiple times in browsers

### ISSUE THREAD

**Issue by eugenemorozov-jb** [JetBrains/ideolog#47]
Have PhpStorm build 183.3975 installed, Ideolog version 183.0.7.0, Windows 10.
Use the following snippet:
```
[http://example.test](example)
```
Click the link.
See the link opened multiple times: http://recordit.co/846hyB3fX0

**Comment by Kyslik** [comment]
(I am the original poster)

Perhaps, because of AdBlocker I can not see the recordit.co; here is the gif

![mayhem](https://user-images.githubusercontent.com/2067589/47641918-9738da00-db67-11e8-87d9-bb27048e389c.gif)

**Comment by lucernae** [comment]
Confirmed this issue. 
I also have this same problems.

PyCharm Pro: 2018.2.3
Ideolog: 182.0.7.0
OS: MacOSX Mojave

I'm here to report, but it turns out this issue already exists, so  I'm just going to bump it.

**Comment by MCMainiac** [comment]
Can confirm for PhpStorm 2018.3 on Windows 10 and Zorin OS 12.4

**Comment by MCMainiac** [comment]
Still exists in PhpStorm 2019.1 on Windows with IdeoLog 191.0.7.0

**Comment by knah** [comment]
An update for the plugin that fixes this issue and improves performance is in the works. It will be available soon-ish.
