### ISSUE TITLE
Paste is not working in "message pattern" field

### ISSUE THREAD

**Issue by rvdginste** [JetBrains/ideolog#66]
In the dialog to edit a log format, paste is not working on the "message pattern" field.

This is on Rider 2019.1.3 on Windows.

**Comment by lordlycastle** [comment]
Also doesn't work on message start pattern.

**Comment by mikemcclaran** [comment]
also doesn't work on Mac

**Comment by mfilippov** [comment]
@rvdginste @lordlycastle @mikemcclaran Could you check the latest vesrion?

**Comment by lordlycastle** [comment]
@mfilippov I can't do it in  JetBrains Rider 2019.3.
Build #RD-193.5233.171, built on December 10, 2019

**Comment by rvdginste** [comment]
@mfilippov Still not working on version "201.0.19.0" of the plugin. Not working on Windows and also not working on linux.

**Comment by mac671** [comment]
Confirmed not working Ideolog 201.0.21.0 installed in Rider Build #RD-193.6494.48, built on February 27, 2020.

This is basically disqualifies this addon for me. The addon in it's current state is a waste of time

**Comment by rvdginste** [comment]
@mac671 I completely agree: this issue is making the plugin useless for me too.

@mfilippov This seems to be at least a _semi-official_ JetBrains plugin since it's hosted inside the JetBrains github. The issue has been reported 8 months ago and seems to be a fairly simple bug to fix. It's a bit disappointing that there is still no fix. Did anyone actually try to fix this?

**Comment by StephenDubliner** [comment]
Looks like it's working now in Rider 2020.1 EAP 6.
