### ISSUE TITLE
Log files with timestamps behind the file extension are not recognised

### ISSUE THREAD

**Issue by graue70** [JetBrains/ideolog#70]
### Problem
Files with names like

- `program.log.2019-08-08`
- `program.log.2019-08-08_15-57`
- `program.log.2019-08-08_15-57-46`

are not recognised as log files. Files with these kinds of names are automatically created by for example the `logging.handlers.TimedRotatingFileHandler` in python after a roll over.

### Solution attempts
1. Check whether the filename contains `.log.` OR ends with `.log`. (There will probably be false positives because of some filenames like `my.log.program.py`.)
1. Check whether there is only some kind of timestamp behind the `.log` extension. (There will probably be false negatives because it is hard to name all kinds of timestamps.)
1. Check whether most of the characters behind `.log` are numbers as this should cover most timestamps (except something like `program.log.2019-August`). (This should result in less false positives than option 1 and less false negatives than option 2.)

**Comment by EmpireDemocratiqueDuPoulpe** [comment]
Hi,
    This issue has been open for some time. I was looking for a solution to the same problem today (some of my log files did not end with `.log`), and I think I have found something.

    In your IntelliJ IDE, go to File > Settings > Editor > File Types. Scroll down the list and click on the record named `Log files`. There, on the right, you can add a custom file extension. Save, and re-open your log file in your IDE, it should work fine. At least, that is the case for me.

**Comment by smirok** [comment]
Hi!

You may want to take a look at https://github.com/JetBrains/ideolog/issues/70#issuecomment-1620155263 for a potential solution to your issue.
Generally, files with the extension `.log` are considered log files.
