### ISSUE TITLE
Please make "Highlight match" feature work

### ISSUE THREAD

**Issue by RoundbootyGuilliman** [JetBrains/ideolog#72]
Not only it would be the most useful feature. at least for me, but it's also very confusing to have the option in your software that doesn't work. I've spent some time trying to figure out what am i doing wrong and why it's not working, until i stumbled upon your wiki page.

And regarding the feature itself, i think colorized logs where every important piece is colorized differently are the most eazy to read, highlighting an entire line is not nearly as useful. Like for example look at IntelliJ's default log output, that's precisely what i was looking for:
![image](https://user-images.githubusercontent.com/29237170/64319025-3bd44580-cfdd-11e9-9aab-1c4cde482756.png)

**Comment by simonm3** [comment]
I agree. I have just spent ages trying to figure out what I am doing wrong. It is absurd to have features that don't work. Would like this feature but also if you have features that don't work then this is confusing - please just remove them.

**Comment by ArtemKar123** [comment]
Added in #169. Will be released in the next version. Thanks for your feedback!
