### ISSUE TITLE
New line is not rendered

### ISSUE THREAD

**Issue by LeeMingX** [JetBrains/ideolog#73]
## Problem

After some configuration, everything worked. But the new log info is not be rendered when I reboot my application. It is strange that it worked again when I enter a <kbd>Del</kbd> on the new empty log file.

## Hope

Hoping you guys do some work to fix that. 

**Thanks for your work again.**

**Comment by ArtemKar123** [comment]
Fixed in #175.  Will be released in the next version. Thanks for your feedback!
