### ISSUE TITLE
Cannot open Log file in PHPStorm 2019.3 on Linux Mint

### ISSUE THREAD

**Issue by dogmaxpeppe** [JetBrains/ideolog#79]
Everytime I try to open a log file, I do a double click and nothing happens. Marking that file as a "text file" works. I'm sure that is an ideolog fault, because when I disable it I can open .log files.

What can I do?

**Comment by gaertnermarkus** [comment]
I deactivated the plugin, and now i can open log files.

Win10

**Comment by knah** [comment]
Please update to Ideolog xxx.0.16.0 (according to your IDE version) and comment if this issue persists for you - a fix for it was made recently.

**Comment by gaertnermarkus** [comment]
Now, Version 193.0.16.0 works fine in 2019.3

**Comment by dogmaxpeppe** [comment]
Yeah, now it works, thank you.
