### ISSUE TITLE
Plugin "Ideolog" is incompatible (target build range is 192.4913 to 192.*).

### ISSUE THREAD

**Issue by magicsunday** [JetBrains/ideolog#81]
Latest PHPStorm reports: 
Plugin Error: Plugin "Ideolog" is incompatible (target build range is 192.4913 to 192.*).

PhpStorm 2019.3
Build #PS-193.5233.101, built on November 27, 2019

Installed version of Ideolog: 192.0.12.0 → 193.0.16.0

**Comment by mfilippov** [comment]
@magicsunday  We have separate  plugin version for 193 please try to update.
