### ISSUE TITLE
Ui unresponsive on files with > 2000 lines

### ISSUE THREAD

**Issue by Romanow88** [JetBrains/ideolog#83]
When having only line highlighting configured, a log file of 2000 lines causes significant UI slowdown when scrolling.

CPU profiling snapshot attached.

[IU-201.4515.24_rdoboni_31.01.2020_14.21.06.zip](https://github.com/JetBrains/ideolog/files/4139558/IU-201.4515.24_rdoboni_31.01.2020_14.21.06.zip)

**Comment by JLuc** [comment]
Unresponsive with 100 lines files allready :-/

**Comment by smirok** [comment]
Fixed in 222.3.2.0, duplicates https://github.com/JetBrains/ideolog/issues/177
