### ISSUE TITLE
Format is not recognized

### ISSUE THREAD

**Issue by maldouk** [JetBrains/ideolog#87]
Hello
So I set up format, date format, etc... this way:
Message pattern: `^\[(\d{2}-\D{3}-\d{4}\s+\d{2}:\d{2}:\d{2})\ (\D*)](.*)$`
Start pattern: ^\\[
Time Format: dd-MMM-yyyy HH:mm:ss
This is for logs looking  like this:
[27-Feb-2020 15:42:14 Europe/Paris] 'message_here'

I know about the rule of having 5 logs in the first 25 lines, it is respected.
While I was setting up, I would see a message saying 'Log format is not recognized'. Now I don't have this message, and I don't see any differences from a file I would've opened without the plugin. 
Am I missing something? (I guess so..) What is it?
Thanks

PS: I would suggest you to add a memocard to the wiki for log and date formats, because it was a bit hazy from the get-go, I had to search quite a bit.

**Comment by aanutter** [comment]
I'm not seeing any code hints after updating yesterday, but the change was just the logo?

IDEoLog version 201.0.20.0

IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 10, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1482M
Cores: 4
Registry: 
Non-Bundled Plugins: anton_dev_ua.PipeTableFormatter, com.alayouni.ansiHighlight, com.intellij.ideolog, com.karateca.jstoolbox, com.thoughtworks.gauge, gherkin, cucumber-java, org.intellij.scala, org.jetbrains.plugins.hocon, org.mayevskiy.intellij.sonar

**Comment by ArtemKar123** [comment]
Fixed in #165. Will be released in the next version. Thanks for your feedback!
