### ISSUE TITLE
log files are read only

### ISSUE THREAD

**Issue by yujin1st** [JetBrains/ideolog#88]
![Снимок экрана 2020-03-09 в 13 59 05](https://user-images.githubusercontent.com/2317913/76184170-34049080-620e-11ea-860c-21e24bdae84f.png)

Why can't i do what i want with file?

**Comment by yujin1st** [comment]
Downloaded files from ftp\ssh via remote panels are also read-only
and i can't mark them as plain!

**Comment by Vampire** [comment]
I would also prefer to have the choice to make log file editable to remove noise that was already fixed and focus on remaining problems.

Maybe the plugin could simply mark the file as read-only using the IntelliJ built-in functionality, so that it can easily be toggled.

**Comment by Vampire** [comment]
Ah, at least I just found a setting that allows editing if the file is under a given threshold which is 16 KiB by default but can be increased.

**Comment by smirok** [comment]
Hi there! There is a setting in `Settings -> Editor -> Log Highlighting -> Allow editing log files smaller than (KB)`. It's allowed to edit files smaller than 16 KB by default, but you can always adjust the threshold for you purposes.

**Comment by jstnfst** [comment]
Simply Remove Ideolog Plugin!

![Image](https://github.com/user-attachments/assets/e7572d8c-aa14-464f-ab66-1716cd5e5885)

**Comment by Vampire** [comment]
That is a pretty non-sense recommendation.
What do you want to achieve with that?
How do I use the ideolog features if I remove ideolog?
This comment does not really make any sense at all.

**Comment by jstnfst** [comment]
Oh! I didn't realize i was in the ideolog plugin project. You're absolutely right. However, i couldn't get the minimum limit thing working, and my 364981 byte file would never become editable. 

i just had to remove the plugin to get it to work. i put all 99999999s in the dialog box and it still wasn't working.

cheers!

**Comment by Vampire** [comment]
Iirc the setting only applies once you close and reopen the file.
