### ISSUE TITLE
"highlight links and code references in logs" doesn't work for single line log records

### ISSUE THREAD

**Issue by ury0005** [JetBrains/ideolog#89]
If it is possible allow code references in single line log records, now those are working for multiline (stack traces) only.
I have code reference in every line of log, in otput console references are linked properly, but not in log viewer.

**Comment by SawJust** [comment]
i  have read part of the source code , in this file com/intellij/ideolog/util/IdeologDocumentContext.kt  ， in class IdeologDocumentContext#detectLogFileFormat() line 73 
`LogFileFormat(sumByMatcher.filter { it.second > 5 }.maxBy { it.second }?.first)`  
it required lines >5 then the file will repaint (The above is only my opinion~)

**Comment by ioannup** [comment]
+1

**Comment by ArtemKar123** [comment]
Fixed in #165. Will be released in the next version. Thanks for your feedback!
