### ISSUE TITLE
Ideolog with Xamarin

### ISSUE THREAD

**Issue by PawKanarek** [JetBrains/ideolog#93]
Hi, I'm migrating my 4 years old project from Windows Visual Studio to Mac Intelij Rider, and during Rider installation I've added this recommended Ideolog plugin. But sadly i don't see any resources on internet about integration Debug/Console.WriteLine methods with this plugin. How my log messages (even from some third party libraries) can be read by this plugin?

My guess right now is to create custom logging mechanism, to save every message in *.log file somewhere on My mac and then finally Ideolog could read this. But that seems to be a heavy job as i run this app on Android/iOS/AppleTv, so i would need to stream every log message from other operating systems to my mac... Any ideas how to handle it easily? I don't want to over engineer it.

**Comment by StefanLobbenmeier** [comment]
Pretty old issue, but I have some comments regarding this:
1. a workaround could be to connect to the app from the command line, then you can easily pipe all output from the console to a file using the ">" operator (e.g. echo "a" > text.log)
2. to actually solve this issue though the requirement is quite different though. I think what you need (and what I was looking for) is a way to apply the settings of this plugin also to the console in the run window. I am pretty sure the [grep plugin](https://plugins.jetbrains.com/plugin/7125-grep-console) is able to do this, so it should also be possible for this plugin to do it.

**Comment by PawKanarek** [comment]
Thanks.
