### ISSUE TITLE
Highlight not working

### ISSUE THREAD

**Issue by pavanpkulkarni** [JetBrains/ideolog#96]
Hello, 

I have a log file with the contents as 

2020-06-10 16:23:13.526 [WARN]  [SOME TEXT] This is a warning
2020-06-10 16:23:14.121 [ERROR]  [ANOTHER TEXT] This is an ERROR
2020-06-10 16:23:17.506 [INFO]  [SOME TEXT] This is info.. use it wisely!

**Message Pattern :** ^([^\\[]+)\\s*(\\[[\\s\\w]+])\\s*(\\[[\\s\\w]+])\\s*(.+)$
**Message Pattern Start:** ^\d
**Time format:** yyyy-MM-dd HH:mm:ss.SSS

**Groups Are:**
Time Capture Group: 1
Severity Capture Group: 2
Category Capture Group : 3

I have verified the Regex online and it matches the test input as well. 

Despite this, I'm unable to see the highlighting in my *.log files. 

Please let me know if I'm missing anything here, 

IJ Version: 2019.2.1 Ultimate

**Comment by ArtemKar123** [comment]
Fixed in #165. Will be released in the next version. Thanks for your feedback!
